/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
description = 'Fineract Progressive Loan Implementation (OSGi impl bundle)'

apply plugin: 'java-library'
apply plugin: 'eclipse'

compileJava {
    dependsOn ':fineract-avro-schemas:buildJavaSdk'
    dependsOn ':fineract-progressive-loan-api:jar'
}

configurations {
    providedRuntime
    providedCompile
    compile() {
        exclude module: 'hibernate-entitymanager'
        exclude module: 'hibernate-validator'
        exclude module: 'activation'
        exclude module: 'bcmail-jdk14'
        exclude module: 'bcprov-jdk14'
        exclude module: 'bctsp-jdk14'
        exclude module: 'c3p0'
        exclude module: 'stax-api'
        exclude module: 'jaxb-api'
        exclude module: 'jaxb-impl'
        exclude module: 'jboss-logging'
        exclude module: 'itext-rtf'
        exclude module: 'classworlds'
    }
    runtime
}

apply from: 'dependencies.gradle'

jar {
    manifest {
        attributes(
                'Bundle-ManifestVersion': '2',
                'Bundle-Name': 'Apache Fineract Progressive Loan Implementation',
                'Bundle-SymbolicName': 'org.apache.fineract.progressiveloan.impl',
                'Bundle-Version': "${project.version}".replace('-SNAPSHOT', '.SNAPSHOT'),
                'Bundle-Description': 'Progressive loan schedule, EMI model, capitalized income residual',
                'Import-Package': '*',
                'Export-Package': 'org.apache.fineract.batch.command.internal,'
                        + 'org.apache.fineract.portfolio.account.data,'
                        + 'org.apache.fineract.portfolio.account.domain,'
                        + 'org.apache.fineract.portfolio.account.service,'
                        + 'org.apache.fineract.portfolio.accountdetails.service,'
                        + 'org.apache.fineract.portfolio.client.api,'
                        + 'org.apache.fineract.portfolio.client.service,'
                        + 'org.apache.fineract.portfolio.shareaccounts.service,'
                        + 'org.apache.fineract.portfolio.configuration,'
                        + 'org.apache.fineract.portfolio.group.api,'
                        + 'org.apache.fineract.portfolio.loanaccount.guarantor.domain,'
                        + 'org.apache.fineract.portfolio.loanaccount.guarantor.service,'
                        + 'org.apache.fineract.portfolio.loanaccount.loanschedule.service,'
                        + 'org.apache.fineract.portfolio.loanaccount.serialization,'
                        + 'org.apache.fineract.portfolio.delinquency.service,'
                        + 'org.apache.fineract.portfolio.loanaccount.api,'
                        + 'org.apache.fineract.portfolio.loanaccount.domain,'
                        + 'org.apache.fineract.portfolio.loanaccount.domain.transactionprocessor.impl,'
                        + 'org.apache.fineract.portfolio.loanaccount.handler,'
                        + 'org.apache.fineract.portfolio.loanaccount.impl.osgi,'
                        + 'org.apache.fineract.portfolio.loanaccount.loanschedule.data,'
                        + 'org.apache.fineract.portfolio.loanaccount.loanschedule.domain,'
                        + 'org.apache.fineract.portfolio.loanaccount.mapper,'
                        + 'org.apache.fineract.portfolio.loanaccount.repository,'
                        + 'org.apache.fineract.portfolio.loanaccount.rescheduleloan.data,'
                        + 'org.apache.fineract.portfolio.loanaccount.service,'
                        + 'org.apache.fineract.portfolio.loanaccount.service.adjustment,'
                        + 'org.apache.fineract.portfolio.loanaccount.service.contracttermination,'
                        + 'org.apache.fineract.portfolio.loanaccount.service.reaging,'
                        + 'org.apache.fineract.portfolio.loanaccount.service.reamortization,'
                        + 'org.apache.fineract.portfolio.loanaccount.util,'
                        + 'org.apache.fineract.portfolio.loanaccount.starter,'
                        + 'org.apache.fineract.portfolio.loanproduct.calc,'
                        + 'org.apache.fineract.portfolio.loanproduct.calc.converter,'
                        + 'org.apache.fineract.portfolio.loanproduct.calc.data,'
                        + 'org.apache.fineract.portfolio.loanproduct.domain,'
                        + 'org.apache.fineract.portfolio.loanproduct.mapper,'
                        + 'org.apache.fineract.portfolio.loanproduct.service,'
                        + 'org.apache.fineract.portfolio.util',
                'Automatic-Module-Name': 'org.apache.fineract.progressiveloan.impl'
                )
    }
}

modernizer {
    ignoreClassNamePatterns = [
        '.*AbstractPersistableCustom',
        '.*EntityTables',
        '.*domain.*'
    ]
}

if (project.hasProperty('env') && project.getProperty('env') == 'eclipse') {
    sourceSets.main.java.outputDir = new File(rootProject.projectDir, "fineract-progressive-loan/impl/bin/main")
}

eclipse {
    project {
        buildCommand([ LaunchConfigHandle: "<project>/.externalToolBuilders/OpenJPA Enhance Builder.launch" ],  'org.eclipse.ui.externaltools.ExternalToolBuilder')
    }
}
