/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
description = 'Fineract Shares API (core residual peel)'

apply plugin: 'java-library'
apply plugin: 'eclipse'
apply from: 'dependencies.gradle'

jar {
    manifest {
        attributes(
                'Bundle-ManifestVersion': '2',
                'Bundle-Name': 'Apache Fineract Shares API',
                'Bundle-SymbolicName': 'org.apache.fineract.shares.api',
                'Bundle-Version': "${project.version}".replace('-SNAPSHOT', '.SNAPSHOT'),
                'Export-Package': 'org.apache.fineract.shares.accounts.api,'
                        + 'org.apache.fineract.shares.accounts.constants,'
                        + 'org.apache.fineract.shares.accounts.data,'
                        + 'org.apache.fineract.shares.accounts.data.request,'
                        + 'org.apache.fineract.shares.accounts.exceptions,'
                        + 'org.apache.fineract.shares.accounts.service,'
                        + 'org.apache.fineract.shares.shareaccounts.data,'
                        + 'org.apache.fineract.shares.shareaccounts.exceptions,'
                        + 'org.apache.fineract.shares.shareaccounts.service,'
                        + 'org.apache.fineract.shares.shareproducts.constants,'
                        + 'org.apache.fineract.shares.shareproducts.data,'
                        + 'org.apache.fineract.shares.shareproducts.exception,'
                        + 'org.apache.fineract.shares.shareproducts.service',
                'Import-Package': 'org.apache.fineract.accounting.common,'
                        + 'org.apache.fineract.accounting.glaccount.data,'
                        + 'org.apache.fineract.accounting.producttoaccountmapping.data,'
                        + 'org.apache.fineract.infrastructure.core.api,'
                        + 'org.apache.fineract.infrastructure.core.data,'
                        + 'org.apache.fineract.infrastructure.core.exception,'
                        + 'org.apache.fineract.infrastructure.core.jersey.serializer.legacy,'
                        + 'org.apache.fineract.infrastructure.core.service,'
                        + 'org.apache.fineract.organisation.monetary.data,'
                        + 'org.apache.fineract.portfolio.accountdetails.data,'
                        + 'org.apache.fineract.portfolio.charge.data,'
                        + 'org.apache.fineract.portfolio.products.data,'
                        + 'org.apache.fineract.portfolio.savings.data,'
                        + 'org.apache.fineract.shares.shareaccounts.domain,'
                        + 'org.apache.fineract.shares.shareproducts,'
                        + 'org.apache.fineract.shares.shareproducts.domain,'
                        + '*',
                'Automatic-Module-Name': 'org.apache.fineract.shares.api'
                )
    }
}
