# Equinox Configuration for fineract-osgi
osgi.noShutdown=true
osgi.console.enable.builtin=true
osgi.bundles.defaultStartLevel=4
osgi.startLevel=6
osgi.clean=true
osgi.framework.extensions=
osgi.framework.shape=jar
osgi.install.area=.
osgi.configuration.area=config
osgi.logfile=logs/equinox.log

# Fineract specific properties
fineract.mode.read.enabled=true
fineract.mode.write.enabled=true
fineract.mode.batch.manager.enabled=true
