/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
description = 'Fineract Clients API (core residual peel)'

apply plugin: 'java-library'
apply plugin: 'eclipse'
apply from: 'dependencies.gradle'

jar {
    manifest {
        attributes(
                'Bundle-ManifestVersion': '2',
                'Bundle-Name': 'Apache Fineract Clients API',
                'Bundle-SymbolicName': 'org.apache.fineract.clients.api',
                'Bundle-Version': "${project.version}".replace('-SNAPSHOT', '.SNAPSHOT'),
                'Export-Package': 'org.apache.fineract.portfolio.client.api.v2.search,'
                        + 'org.apache.fineract.portfolio.client.command,'
                        + 'org.apache.fineract.portfolio.client.data,'
                        + 'org.apache.fineract.portfolio.client.moduleapi,'
                        + 'org.apache.fineract.portfolio.client.service,'
                        + 'org.apache.fineract.portfolio.client.service.search,'
                        + 'org.apache.fineract.portfolio.client.service.search.domain,'
                        + 'org.apache.fineract.portfolio.client.service.search.mapper',
                'Import-Package': 'org.apache.fineract.infrastructure.codes.data,'
                        + 'org.apache.fineract.infrastructure.core.api,'
                        + 'org.apache.fineract.infrastructure.core.data,'
                        + 'org.apache.fineract.infrastructure.core.domain,'
                        + 'org.apache.fineract.infrastructure.core.exception,'
                        + 'org.apache.fineract.infrastructure.core.service,'
                        + 'org.apache.fineract.organisation.monetary.data,'
                        + 'org.apache.fineract.portfolio.charge.data,'
                        + 'org.apache.fineract.portfolio.client.api,'
                        + 'org.apache.fineract.portfolio.client.domain,'
                        + 'org.apache.fineract.portfolio.paymentdetail.data,'
                        + 'org.apache.fineract.portfolio.paymenttype.data,'
                        + '*',
                'Automatic-Module-Name': 'org.apache.fineract.clients.api'
                )
    }
}
