/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements. See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership. The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
description = 'Fineract Loan API (OSGi interface bundle)'

apply plugin: 'java-library'
apply plugin: 'eclipse'

apply from: 'dependencies.gradle'

jar {
    manifest {
        attributes(
                'Bundle-ManifestVersion': '2',
                'Bundle-Name': 'Apache Fineract Loan API',
                'Bundle-SymbolicName': 'org.apache.fineract.loan.api',
                'Bundle-Version': "${project.version}".replace('-SNAPSHOT', '.SNAPSHOT'),
                'Bundle-Description': 'Loan contracts (ports, pure DTOs, exceptions)',
                'Export-Package': 'org.apache.fineract.infrastructure.event.business.domain.loan,'
                        + 'org.apache.fineract.infrastructure.event.business.domain.loan.charge,'
                        + 'org.apache.fineract.infrastructure.event.business.domain.loan.product,'
                        + 'org.apache.fineract.infrastructure.event.business.domain.loan.reaging,'
                        + 'org.apache.fineract.infrastructure.event.business.domain.loan.reamortization,'
                        + 'org.apache.fineract.infrastructure.event.business.domain.loan.repayment,'
                        + 'org.apache.fineract.infrastructure.event.business.domain.loan.transaction,'
                        + 'org.apache.fineract.infrastructure.event.business.domain.loan.transaction.reaging,'
                        + 'org.apache.fineract.infrastructure.event.business.domain.loan.transaction.reamortization,'
                        + 'org.apache.fineract.portfolio.accountdetails.data,'
                        + 'org.apache.fineract.portfolio.delinquency.api,'
                        + 'org.apache.fineract.portfolio.delinquency.api.data,'
                        + 'org.apache.fineract.portfolio.delinquency.data,'
                        + 'org.apache.fineract.portfolio.delinquency.domain,'
                        + 'org.apache.fineract.portfolio.delinquency.exception,'
                        + 'org.apache.fineract.portfolio.delinquency.helper,'
                        + 'org.apache.fineract.portfolio.delinquency.spi,'
                        + 'org.apache.fineract.portfolio.delinquency.validator,'
                        + 'org.apache.fineract.portfolio.interestpauses.data,'
                        + 'org.apache.fineract.portfolio.interestpauses.service,'
                        + 'org.apache.fineract.portfolio.loanaccount.api,'
                        + 'org.apache.fineract.portfolio.loanaccount.api.pointintime,'
                        + 'org.apache.fineract.portfolio.loanaccount.api.pointintime.data,'
                        + 'org.apache.fineract.portfolio.loanaccount.api.request,'
                        + 'org.apache.fineract.portfolio.loanaccount.command,'
                        + 'org.apache.fineract.portfolio.loanaccount.data,'
                        + 'org.apache.fineract.portfolio.loanaccount.domain,'
                        + 'org.apache.fineract.portfolio.loanaccount.domain.arrears,'
                        + 'org.apache.fineract.portfolio.loanaccount.domain.reaging,'
                        + 'org.apache.fineract.portfolio.loanaccount.domain.reamortization,'
                        + 'org.apache.fineract.portfolio.loanaccount.domain.transactionprocessor,'
                        + 'org.apache.fineract.portfolio.loanaccount.exception,'
                        + 'org.apache.fineract.portfolio.loanaccount.guarantor,'
                        + 'org.apache.fineract.portfolio.loanaccount.guarantor.command,'
                        + 'org.apache.fineract.portfolio.loanaccount.guarantor.data,'
                        + 'org.apache.fineract.portfolio.loanaccount.guarantor.domain,'
                        + 'org.apache.fineract.portfolio.loanaccount.guarantor.exception,'
                        + 'org.apache.fineract.portfolio.loanaccount.guarantor.service,'
                        + 'org.apache.fineract.portfolio.loanaccount.loanschedule.data,'
                        + 'org.apache.fineract.portfolio.loanaccount.loanschedule.domain,'
                        + 'org.apache.fineract.portfolio.loanaccount.loanschedule.exception,'
                        + 'org.apache.fineract.portfolio.loanaccount.loanschedule.service,'
                        + 'org.apache.fineract.portfolio.loanaccount.moduleapi,'
                        + 'org.apache.fineract.portfolio.loanaccount.rescheduleloan,'
                        + 'org.apache.fineract.portfolio.loanaccount.rescheduleloan.data,'
                        + 'org.apache.fineract.portfolio.loanaccount.rescheduleloan.domain,'
                        + 'org.apache.fineract.portfolio.loanaccount.rescheduleloan.exception,'
                        + 'org.apache.fineract.portfolio.loanaccount.rescheduleloan.service,'
                        + 'org.apache.fineract.portfolio.loanaccount.serialization,'
                        + 'org.apache.fineract.portfolio.loanaccount.service,'
                        + 'org.apache.fineract.portfolio.loanproduct,'
                        + 'org.apache.fineract.portfolio.loanproduct.data,'
                        + 'org.apache.fineract.portfolio.loanproduct.domain,'
                        + 'org.apache.fineract.portfolio.loanproduct.exception,'
                        + 'org.apache.fineract.portfolio.loanproduct.productmix.command,'
                        + 'org.apache.fineract.portfolio.loanproduct.productmix.data,'
                        + 'org.apache.fineract.portfolio.loanproduct.productmix.exception,'
                        + 'org.apache.fineract.portfolio.loanproduct.productmix.service,'
                        + 'org.apache.fineract.portfolio.loanproduct.service',
                'Import-Package': 'org.apache.fineract.command.core,'
                        + 'org.apache.fineract.infrastructure.event.business.domain,'
                        + 'org.apache.fineract.accounting.common,'
                        + 'org.apache.fineract.accounting.journalentry.data,'
                        + 'org.apache.fineract.infrastructure.codes.data,'
                        + 'org.apache.fineract.infrastructure.core.api,'
                        + 'org.apache.fineract.infrastructure.core.data,'
                        + 'org.apache.fineract.infrastructure.core.domain,'
                        + 'org.apache.fineract.infrastructure.core.exception,'
                        + 'org.apache.fineract.infrastructure.core.service,'
                        + 'org.apache.fineract.organisation.monetary.data,'
                        + 'org.apache.fineract.organisation.monetary.domain,'
                        + 'org.apache.fineract.organisation.office.data,'
                        + 'org.apache.fineract.organisation.staff.data,'
                        + 'org.apache.fineract.portfolio.account.data,'
                        + 'org.apache.fineract.portfolio.accountdetails.service,'
                        + 'org.apache.fineract.portfolio.calendar.data,'
                        + 'org.apache.fineract.portfolio.client.data,'
                        + 'org.apache.fineract.portfolio.charge.data,'
                        + 'org.apache.fineract.portfolio.charge.moduleapi,'
                        + 'org.apache.fineract.portfolio.common.domain,'
                        + 'org.apache.fineract.portfolio.floatingrates.data,'
                        + 'org.apache.fineract.portfolio.fund.data,'
                        + 'org.apache.fineract.portfolio.note.data,'
                        + 'org.apache.fineract.portfolio.rate.data,'
                        + 'org.apache.fineract.portfolio.paymentdetail.data,'
                        + 'org.apache.fineract.portfolio.paymenttype.data,'
                        + 'org.apache.fineract.portfolio.savings.data,'
                        + 'org.apache.fineract.validation.constraints,'
                        + '*',
                'Automatic-Module-Name': 'org.apache.fineract.loan.api'
                )
    }
}

if (project.hasProperty('env') && project.getProperty('env') == 'eclipse') {
    sourceSets.main.java.outputDir = new File(rootProject.projectDir, "fineract-loan/api/bin/main")
}
